title: Mehdi Benammar – Opefitoo
description: Personal website of Mehdi Benammar
url: "https://opefitoo.github.io"
baseurl: ""
email: mehdi@benammar.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Social media
social:
  linkedin: mehdi-benammar
  github: opefitoo
  email: mehdi@benammar.com

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - docker-compose.yml
  - Dockerfile
  - nginx
  - certbot
