version: '3'

services:
  web:
    image: nginx:alpine
    container_name: opefitoo-web
    ports:
      - "3001:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt
  #     - ./data/certbot/www:/var/www/certbot
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email info@opefitoo.com -d opefitoo.org --agree-tos
